// Code generated by mockery. DO NOT EDIT.

package biz

import (
	biz "github.com/acepanel/panel/v3/internal/biz"
	mock "github.com/stretchr/testify/mock"
)

// UserPasskeyRepo is an autogenerated mock type for the UserPasskeyRepo type
type UserPasskeyRepo struct {
	mock.Mock
}

type UserPasskeyRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UserPasskeyRepo) EXPECT() *UserPasskeyRepo_Expecter {
	return &UserPasskeyRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: passkey
func (_m *UserPasskeyRepo) Create(passkey *biz.UserPasskey) error {
	ret := _m.Called(passkey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*biz.UserPasskey) error); ok {
		r0 = rf(passkey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserPasskeyRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserPasskeyRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - passkey *biz.UserPasskey
func (_e *UserPasskeyRepo_Expecter) Create(passkey interface{}) *UserPasskeyRepo_Create_Call {
	return &UserPasskeyRepo_Create_Call{Call: _e.mock.On("Create", passkey)}
}

func (_c *UserPasskeyRepo_Create_Call) Run(run func(passkey *biz.UserPasskey)) *UserPasskeyRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*biz.UserPasskey))
	})
	return _c
}

func (_c *UserPasskeyRepo_Create_Call) Return(_a0 error) *UserPasskeyRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserPasskeyRepo_Create_Call) RunAndReturn(run func(*biz.UserPasskey) error) *UserPasskeyRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: userID, id
func (_m *UserPasskeyRepo) Delete(userID uint, id uint) error {
	ret := _m.Called(userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserPasskeyRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserPasskeyRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - userID uint
//   - id uint
func (_e *UserPasskeyRepo_Expecter) Delete(userID interface{}, id interface{}) *UserPasskeyRepo_Delete_Call {
	return &UserPasskeyRepo_Delete_Call{Call: _e.mock.On("Delete", userID, id)}
}

func (_c *UserPasskeyRepo_Delete_Call) Run(run func(userID uint, id uint)) *UserPasskeyRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *UserPasskeyRepo_Delete_Call) Return(_a0 error) *UserPasskeyRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserPasskeyRepo_Delete_Call) RunAndReturn(run func(uint, uint) error) *UserPasskeyRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllByUserID provides a mock function with given fields: userID
func (_m *UserPasskeyRepo) DeleteAllByUserID(userID uint) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserPasskeyRepo_DeleteAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllByUserID'
type UserPasskeyRepo_DeleteAllByUserID_Call struct {
	*mock.Call
}

// DeleteAllByUserID is a helper method to define mock.On call
//   - userID uint
func (_e *UserPasskeyRepo_Expecter) DeleteAllByUserID(userID interface{}) *UserPasskeyRepo_DeleteAllByUserID_Call {
	return &UserPasskeyRepo_DeleteAllByUserID_Call{Call: _e.mock.On("DeleteAllByUserID", userID)}
}

func (_c *UserPasskeyRepo_DeleteAllByUserID_Call) Run(run func(userID uint)) *UserPasskeyRepo_DeleteAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *UserPasskeyRepo_DeleteAllByUserID_Call) Return(_a0 error) *UserPasskeyRepo_DeleteAllByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserPasskeyRepo_DeleteAllByUserID_Call) RunAndReturn(run func(uint) error) *UserPasskeyRepo_DeleteAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCredentialID provides a mock function with given fields: credentialID
func (_m *UserPasskeyRepo) GetByCredentialID(credentialID []byte) (*biz.UserPasskey, *biz.User, error) {
	ret := _m.Called(credentialID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCredentialID")
	}

	var r0 *biz.UserPasskey
	var r1 *biz.User
	var r2 error
	if rf, ok := ret.Get(0).(func([]byte) (*biz.UserPasskey, *biz.User, error)); ok {
		return rf(credentialID)
	}
	if rf, ok := ret.Get(0).(func([]byte) *biz.UserPasskey); ok {
		r0 = rf(credentialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.UserPasskey)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) *biz.User); ok {
		r1 = rf(credentialID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*biz.User)
		}
	}

	if rf, ok := ret.Get(2).(func([]byte) error); ok {
		r2 = rf(credentialID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserPasskeyRepo_GetByCredentialID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCredentialID'
type UserPasskeyRepo_GetByCredentialID_Call struct {
	*mock.Call
}

// GetByCredentialID is a helper method to define mock.On call
//   - credentialID []byte
func (_e *UserPasskeyRepo_Expecter) GetByCredentialID(credentialID interface{}) *UserPasskeyRepo_GetByCredentialID_Call {
	return &UserPasskeyRepo_GetByCredentialID_Call{Call: _e.mock.On("GetByCredentialID", credentialID)}
}

func (_c *UserPasskeyRepo_GetByCredentialID_Call) Run(run func(credentialID []byte)) *UserPasskeyRepo_GetByCredentialID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *UserPasskeyRepo_GetByCredentialID_Call) Return(_a0 *biz.UserPasskey, _a1 *biz.User, _a2 error) *UserPasskeyRepo_GetByCredentialID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UserPasskeyRepo_GetByCredentialID_Call) RunAndReturn(run func([]byte) (*biz.UserPasskey, *biz.User, error)) *UserPasskeyRepo_GetByCredentialID_Call {
	_c.Call.Return(run)
	return _c
}

// HasAny provides a mock function with no fields
func (_m *UserPasskeyRepo) HasAny() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasAny")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPasskeyRepo_HasAny_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasAny'
type UserPasskeyRepo_HasAny_Call struct {
	*mock.Call
}

// HasAny is a helper method to define mock.On call
func (_e *UserPasskeyRepo_Expecter) HasAny() *UserPasskeyRepo_HasAny_Call {
	return &UserPasskeyRepo_HasAny_Call{Call: _e.mock.On("HasAny")}
}

func (_c *UserPasskeyRepo_HasAny_Call) Run(run func()) *UserPasskeyRepo_HasAny_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UserPasskeyRepo_HasAny_Call) Return(_a0 bool, _a1 error) *UserPasskeyRepo_HasAny_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserPasskeyRepo_HasAny_Call) RunAndReturn(run func() (bool, error)) *UserPasskeyRepo_HasAny_Call {
	_c.Call.Return(run)
	return _c
}

// HasPasskey provides a mock function with given fields: userID
func (_m *UserPasskeyRepo) HasPasskey(userID uint) (bool, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for HasPasskey")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (bool, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) bool); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPasskeyRepo_HasPasskey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPasskey'
type UserPasskeyRepo_HasPasskey_Call struct {
	*mock.Call
}

// HasPasskey is a helper method to define mock.On call
//   - userID uint
func (_e *UserPasskeyRepo_Expecter) HasPasskey(userID interface{}) *UserPasskeyRepo_HasPasskey_Call {
	return &UserPasskeyRepo_HasPasskey_Call{Call: _e.mock.On("HasPasskey", userID)}
}

func (_c *UserPasskeyRepo_HasPasskey_Call) Run(run func(userID uint)) *UserPasskeyRepo_HasPasskey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *UserPasskeyRepo_HasPasskey_Call) Return(_a0 bool, _a1 error) *UserPasskeyRepo_HasPasskey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserPasskeyRepo_HasPasskey_Call) RunAndReturn(run func(uint) (bool, error)) *UserPasskeyRepo_HasPasskey_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: userID
func (_m *UserPasskeyRepo) List(userID uint) ([]*biz.UserPasskey, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*biz.UserPasskey
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]*biz.UserPasskey, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []*biz.UserPasskey); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.UserPasskey)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPasskeyRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type UserPasskeyRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - userID uint
func (_e *UserPasskeyRepo_Expecter) List(userID interface{}) *UserPasskeyRepo_List_Call {
	return &UserPasskeyRepo_List_Call{Call: _e.mock.On("List", userID)}
}

func (_c *UserPasskeyRepo_List_Call) Run(run func(userID uint)) *UserPasskeyRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *UserPasskeyRepo_List_Call) Return(_a0 []*biz.UserPasskey, _a1 error) *UserPasskeyRepo_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserPasskeyRepo_List_Call) RunAndReturn(run func(uint) ([]*biz.UserPasskey, error)) *UserPasskeyRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastUsed provides a mock function with given fields: credentialID
func (_m *UserPasskeyRepo) UpdateLastUsed(credentialID []byte) error {
	ret := _m.Called(credentialID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(credentialID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserPasskeyRepo_UpdateLastUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastUsed'
type UserPasskeyRepo_UpdateLastUsed_Call struct {
	*mock.Call
}

// UpdateLastUsed is a helper method to define mock.On call
//   - credentialID []byte
func (_e *UserPasskeyRepo_Expecter) UpdateLastUsed(credentialID interface{}) *UserPasskeyRepo_UpdateLastUsed_Call {
	return &UserPasskeyRepo_UpdateLastUsed_Call{Call: _e.mock.On("UpdateLastUsed", credentialID)}
}

func (_c *UserPasskeyRepo_UpdateLastUsed_Call) Run(run func(credentialID []byte)) *UserPasskeyRepo_UpdateLastUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *UserPasskeyRepo_UpdateLastUsed_Call) Return(_a0 error) *UserPasskeyRepo_UpdateLastUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserPasskeyRepo_UpdateLastUsed_Call) RunAndReturn(run func([]byte) error) *UserPasskeyRepo_UpdateLastUsed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSignCount provides a mock function with given fields: credentialID, signCount
func (_m *UserPasskeyRepo) UpdateSignCount(credentialID []byte, signCount uint32) error {
	ret := _m.Called(credentialID, signCount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSignCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, uint32) error); ok {
		r0 = rf(credentialID, signCount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserPasskeyRepo_UpdateSignCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSignCount'
type UserPasskeyRepo_UpdateSignCount_Call struct {
	*mock.Call
}

// UpdateSignCount is a helper method to define mock.On call
//   - credentialID []byte
//   - signCount uint32
func (_e *UserPasskeyRepo_Expecter) UpdateSignCount(credentialID interface{}, signCount interface{}) *UserPasskeyRepo_UpdateSignCount_Call {
	return &UserPasskeyRepo_UpdateSignCount_Call{Call: _e.mock.On("UpdateSignCount", credentialID, signCount)}
}

func (_c *UserPasskeyRepo_UpdateSignCount_Call) Run(run func(credentialID []byte, signCount uint32)) *UserPasskeyRepo_UpdateSignCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(uint32))
	})
	return _c
}

func (_c *UserPasskeyRepo_UpdateSignCount_Call) Return(_a0 error) *UserPasskeyRepo_UpdateSignCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserPasskeyRepo_UpdateSignCount_Call) RunAndReturn(run func([]byte, uint32) error) *UserPasskeyRepo_UpdateSignCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserPasskeyRepo creates a new instance of UserPasskeyRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserPasskeyRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserPasskeyRepo {
	mock := &UserPasskeyRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
